package com.flameking.ourwechat.entity;

import java.util.Date;

public class Friend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.id
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.accept_date
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    private Date acceptDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.avatar_url
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    private String avatarUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.friend_id
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    private Long friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.remark
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.self_id
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    private Long selfId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.status
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.id
     *
     * @return the value of friend.id
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.id
     *
     * @param id the value for friend.id
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.accept_date
     *
     * @return the value of friend.accept_date
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    public Date getAcceptDate() {
        return acceptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.accept_date
     *
     * @param acceptDate the value for friend.accept_date
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    public void setAcceptDate(Date acceptDate) {
        this.acceptDate = acceptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.avatar_url
     *
     * @return the value of friend.avatar_url
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.avatar_url
     *
     * @param avatarUrl the value for friend.avatar_url
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.friend_id
     *
     * @return the value of friend.friend_id
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    public Long getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.friend_id
     *
     * @param friendId the value for friend.friend_id
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    public void setFriendId(Long friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.remark
     *
     * @return the value of friend.remark
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.remark
     *
     * @param remark the value for friend.remark
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.self_id
     *
     * @return the value of friend.self_id
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    public Long getSelfId() {
        return selfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.self_id
     *
     * @param selfId the value for friend.self_id
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    public void setSelfId(Long selfId) {
        this.selfId = selfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.status
     *
     * @return the value of friend.status
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.status
     *
     * @param status the value for friend.status
     *
     * @mbggenerated Mon Jun 06 22:01:55 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}