package com.flameking.ourwechat.entity;

import java.util.Date;

public class Group {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.id
     *
     * @mbggenerated Mon Jun 06 22:01:42 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.avatar_url
     *
     * @mbggenerated Mon Jun 06 22:01:42 CST 2022
     */
    private String avatarUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.create_date
     *
     * @mbggenerated Mon Jun 06 22:01:42 CST 2022
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.name
     *
     * @mbggenerated Mon Jun 06 22:01:42 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.id
     *
     * @return the value of group.id
     *
     * @mbggenerated Mon Jun 06 22:01:42 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.id
     *
     * @param id the value for group.id
     *
     * @mbggenerated Mon Jun 06 22:01:42 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.avatar_url
     *
     * @return the value of group.avatar_url
     *
     * @mbggenerated Mon Jun 06 22:01:42 CST 2022
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.avatar_url
     *
     * @param avatarUrl the value for group.avatar_url
     *
     * @mbggenerated Mon Jun 06 22:01:42 CST 2022
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.create_date
     *
     * @return the value of group.create_date
     *
     * @mbggenerated Mon Jun 06 22:01:42 CST 2022
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.create_date
     *
     * @param createDate the value for group.create_date
     *
     * @mbggenerated Mon Jun 06 22:01:42 CST 2022
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.name
     *
     * @return the value of group.name
     *
     * @mbggenerated Mon Jun 06 22:01:42 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.name
     *
     * @param name the value for group.name
     *
     * @mbggenerated Mon Jun 06 22:01:42 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}