package com.flameking.ourwechat.entity;

public class GroupUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user.id
     *
     * @mbggenerated Mon Jun 06 22:01:30 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user.group_id
     *
     * @mbggenerated Mon Jun 06 22:01:30 CST 2022
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_user.user_id
     *
     * @mbggenerated Mon Jun 06 22:01:30 CST 2022
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user.id
     *
     * @return the value of group_user.id
     *
     * @mbggenerated Mon Jun 06 22:01:30 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user.id
     *
     * @param id the value for group_user.id
     *
     * @mbggenerated Mon Jun 06 22:01:30 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user.group_id
     *
     * @return the value of group_user.group_id
     *
     * @mbggenerated Mon Jun 06 22:01:30 CST 2022
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user.group_id
     *
     * @param groupId the value for group_user.group_id
     *
     * @mbggenerated Mon Jun 06 22:01:30 CST 2022
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_user.user_id
     *
     * @return the value of group_user.user_id
     *
     * @mbggenerated Mon Jun 06 22:01:30 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_user.user_id
     *
     * @param userId the value for group_user.user_id
     *
     * @mbggenerated Mon Jun 06 22:01:30 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}