server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ourwechat?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true

logging:
  level:
    com.flameking.ourwechat.mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.flamking.ourwechat.entity #实体类所在的包