wechat:
  time:
    unit: 12
    offset: 5
  salt: 0123456789flameking@

server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ourwechat?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
        # 连接池中的最大空闲连接 默认
        max-idle: 8
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: 5000
    timeout: 5000
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: 2711554770@qq.com
    password: wjkqourdxaqvdcha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    com.flameking.ourwechat.mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.flamking.ourwechat.entity #实体类所在的包